apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: dockersohna/todo-app:v1.0
          envFrom:
            - configMapRef:
                name: appsettings
            - secretRef:
                name: dbsecret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
              cpu: 250m
          ports:
            - containerPort: 3000
